# Generated by Django 5.2.18 on 2026-10-09 21:02

import django.db.models.deletion
import intake.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('has_text_layer', models.BooleanField(default=True)),
                ('preview_image', models.ImageField(blank=True, max_length=500, upload_to=intake.models.page_preview_path)),
            ],
            options={
                'ordering': ['document_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('file', models.ImageField(max_length=500, upload_to=intake.models.image_upload_path)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('src', models.CharField(blank=True, max_length=2000)),
                ('alt', models.TextField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('decorative', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='intake.documentpage')),
            ],
            options={
                'ordering': ['page_id', 'index'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('rows', models.JSONField(default=list)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('header_guess', models.JSONField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='intake.documentpage')),
            ],
            options={
                'ordering': ['page_id', 'index'],
            },
        ),
        migrations.CreateModel(
            name='IntakeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('default_scope', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'intake batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel workbook'), ('html', 'Web page'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('origin', models.CharField(choices=[('upload', 'Upload'), ('url', 'URL'), ('from_workbook', 'Link from workbook'), ('from_page', 'Link from page')], max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('final_url', models.URLField(blank=True, max_length=2000)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('stored_file', models.FileField(blank=True, max_length=500, upload_to=intake.models.document_upload_path)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=100)),
                ('year_hint', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('fetching', 'Fetching'), ('normalizing', 'Normalizing'), ('ready', 'Ready'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='intake.intakebatch')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='intake.sourcedocument')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='intake.sourcedocument')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('gave_up', 'Gave up')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('run_after', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='intake.sourcedocument')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_events', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='intake.intakebatch')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='intake.sourcedocument')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='documentpage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='intake.sourcedocument'),
        ),
        migrations.CreateModel(
            name='CandidateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('context', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_links', to='intake.sourcedocument')),
                ('queued_as', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_from_links', to='intake.sourcedocument')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='intake_documentpage_unique_document_number'),
        ),
        migrations.AddConstraint(
            model_name='candidatelink',
            constraint=models.UniqueConstraint(fields=('document', 'url'), name='intake_candidatelink_unique_document_url'),
        ),
    ]
