# Generated by Django 5.2.17 on 2026-10-05

import django.core.validators
import django.db.models.deletion
import imports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="DatasetImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("jurisdiction", models.CharField(blank=True, max_length=100)),
                ("reporting_year", models.PositiveIntegerField(blank=True, null=True)),
                ("framework_version", models.CharField(blank=True, max_length=50)),
                ("uploaded_file", models.FileField(upload_to=imports.models.import_upload_path, validators=[django.core.validators.FileExtensionValidator(["xlsx"])])),
                ("original_filename", models.CharField(max_length=255)),
                ("file_sha256", models.CharField(db_index=True, max_length=64)),
                ("status", models.CharField(choices=[("uploaded", "Uploaded"), ("validating", "Validating"), ("needs_correction", "Needs correction"), ("ready", "Ready for review"), ("approved", "Approved and published"), ("rejected", "Rejected"), ("failed", "Processing failed")], db_index=True, default="uploaded", max_length=30)),
                ("selected_sheets", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("validation_warnings", models.JSONField(blank=True, default=list)),
                ("cluster_summary", models.JSONField(blank=True, default=dict)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="eim_reviews", to=settings.AUTH_USER_MODEL)),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="eim_uploads", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=80)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ("dataset_import", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="imports.datasetimport")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PublishedRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sheet_name", models.CharField(db_index=True, max_length=100)),
                ("source_row", models.PositiveIntegerField()),
                ("record_key", models.CharField(blank=True, db_index=True, max_length=200)),
                ("payload", models.JSONField(default=dict)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("dataset_import", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="published_records", to="imports.datasetimport")),
            ],
            options={
                "ordering": ["sheet_name", "source_row"],
                "constraints": [models.UniqueConstraint(fields=("dataset_import", "sheet_name", "source_row"), name="unique_published_source_row")],
            },
        ),
        migrations.CreateModel(
            name="StagedRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sheet_name", models.CharField(db_index=True, max_length=100)),
                ("source_row", models.PositiveIntegerField()),
                ("record_key", models.CharField(blank=True, db_index=True, max_length=200)),
                ("payload", models.JSONField(default=dict)),
                ("is_valid", models.BooleanField(db_index=True, default=True)),
                ("issues", models.JSONField(blank=True, default=list)),
                ("dataset_import", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="staged_records", to="imports.datasetimport")),
            ],
            options={
                "ordering": ["sheet_name", "source_row"],
                "constraints": [models.UniqueConstraint(fields=("dataset_import", "sheet_name", "source_row"), name="unique_staged_source_row")],
            },
        ),
    ]
